class MockContent {
  static const services = [
    {
      'id': 'service_1',
      'title': 'جلسات التخاطب',
      'description': 'جلسات فردية لتحسين النطق والتواصل.',
      'imageUrl': 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800',
      'benefit': 'خطة علاجية مخصصة لكل طفل',
      'icon': 'record_voice_over',
      'overview': 'جلسات تخاطب فردية يقدمها أخصائيو نطق معتمدون لتحسين النطق واللغة والتواصل عند الأطفال.',
      'whoIsItFor': 'الأطفال الذين يعانون من تأخر أو اضطراب في النطق أو اللغة، أو صعوبات في التواصل.',
      'benefits': ['خطة علاجية مخصصة لكل طفل', 'متابعة دورية وتقارير تقدم', 'أنشطة تفاعلية داخل الجلسة'],
      'howItWorks': ['تقييم أولي لمستوى النطق واللغة', 'وضع خطة علاجية فردية', 'جلسات أسبوعية مع متابعة مستمرة'],
      'duration': '٤٥–٦٠ دقيقة لكل جلسة',
      'requirements': 'لا يوجد متطلبات مسبقة',
      'pricing': 'يبدأ من ١٢٠ ج.م / جلسة',
    },
    {
      'id': 'service_2',
      'title': 'تنمية المهارات',
      'description': 'أنشطة تفاعلية لتنمية الإدراك والمهارات.',
      'imageUrl': 'https://images.unsplash.com/photo-1503455637927-730bce8583c0?w=800',
      'benefit': 'تنمية الانتباه والتركيز والإدراك',
      'icon': 'psychology',
      'overview': 'برامج تفاعلية لتنمية المهارات الإدراكية والانتباه والتركيز والمهارات الحياتية لدى الأطفال.',
      'whoIsItFor': 'الأطفال الذين يحتاجون إلى تعزيز الانتباه أو المهارات الإدراكية أو التنظيم.',
      'benefits': ['تحسين الانتباه والتركيز', 'تنمية المهارات الإدراكية', 'أنشطة ممتعة ومناسبة للعمر'],
      'howItWorks': ['تقييم المهارات الحالية', 'برنامج تدريبي أسبوعي', 'تقييم تقدم دوري'],
      'duration': '٤٥ دقيقة لكل جلسة',
      'requirements': 'تقييم مبدئي (إن وُجد)',
      'pricing': 'يبدأ من ١٠٠ ج.م / جلسة',
    },
    {
      'id': 'service_3',
      'title': 'جلسات المتابعة',
      'description': 'متابعة دورية لتقييم التقدّم.',
      'imageUrl': 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800',
      'benefit': 'تقييم مستمر وتعديل الخطة',
      'icon': 'assignment',
      'overview': 'جلسات متابعة دورية لتقييم تقدم الطفل وتعديل خطة التدخل وفقاً للنتائج.',
      'whoIsItFor': 'الأطفال الذين يخضعون بالفعل لبرنامج علاجي أو تدريبي ويحتاجون متابعة منتظمة.',
      'benefits': ['تقييم تقدم دوري', 'تعديل الخطة حسب النتائج', 'تقارير مفصلة للأهل'],
      'howItWorks': ['مراجعة التقدم منذ آخر جلسة', 'تعديل الأهداف والأنشطة', 'تقرير وتوصيات للأهل'],
      'duration': '٣٠–٤٥ دقيقة',
      'requirements': 'أن يكون الطفل ضمن برنامج علاجي سابق',
      'pricing': 'يبدأ من ٨٠ ج.م / جلسة',
    },
  ];

  static const articles = [
    {
      'id': 'article_1',
      'title': 'كيف تطور مهارات النطق لطفلك؟',
      'description': 'نصائح عملية يومية لتحسين النطق.',
      'imageUrl': 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
      'content':
          'ابدأ بأنشطة بسيطة تعتمد على التكرار والملاحظة. خصص وقتاً يومياً للتمارين الصوتية من خلال اللعب والتقليد. حاول دائماً تشجيع الطفل على الكلام حتى لو كانت مخارج الحروف غير دقيقة في البداية.',
    },
    {
      'id': 'article_2',
      'title': 'ألعاب تنمية الانتباه والتركيز',
      'description': 'أفضل ألعاب محفّزة للانتباه.',
      'imageUrl': 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
      'content':
          'اللعب جزء أساسي من التعلم. جرّب ألعاب المطابقة والترتيب البسيطة. الألوان والأشكال تجذب انتباه الطفل وتساعده على تمييز الفوارق، مما يطور قدراته العقلية بشكل ملحوظ.',
    },
    {
      'id': 'article_3',
      'title': 'أهمية التقييم المبكر',
      'description': 'لماذا التقييم المبكر يصنع فارقاً؟',
      'imageUrl': 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800',
      'content':
          'يساعد التقييم المبكر في تحديد الاحتياجات ووضع خطة مناسبة. كلما بدأنا في مرحلة مبكرة، كانت النتائج أفضل وأسرع في تحسن مهارات الطفل اللغوية والاجتماعية.',
    },
  ];

  static const notifications = [
    {
      'id': 'notif_1',
      'title': 'موعد الجلسة',
      'message': 'لديك جلسة بعد 30 دقيقة مع الأخصائي.',
      'time': 'منذ 1 دقيقة',
      'isRead': false,
    },
    {
      'id': 'notif_2',
      'title': 'نتيجة اختبار جديد',
      'message': 'تم حفظ نتائج اختبار التمييز السمعي.',
      'time': 'منذ 5 دقائق',
      'isRead': true,
    },
  ];

  static const appointment = {
    'id': 'app_1',
    'status': 'UPCOMING',
    'date': 'السبت 2 نوفمبر • 12:00 مساءً',
    'title': 'جلسة تخاطب',
    'type': 'فيديو',
    'doctorName': 'د/ سارة أحمد',
    'doctorImage': 'https://images.unsplash.com/photo-1559839734-2b71f1536783?w=800',
    'price': '120 ج.م',
    'notes': 'يرجى تجهيز الطفل قبل الجلسة بـ 10 دقائق وتوفير بيئة هادئة.',
  };

  static const childProfile = {
    'id': 'mock_child_1',
    'name': 'عمر محمد',
    'age': '6 سنوات',
    'status': 'تخاطب',
    'progress': 0.68,
  };

  static const doctors = [
    {
      'id': 'doc_1',
      'name': 'د/ سارة أحمد',
      'specialty': 'أخصائي تخاطب ونطق',
      'rating': 4.9,
      'reviewsCount': 150,
      'image': 'https://images.unsplash.com/photo-1559839734-2b71f1536783?w=800',
      'about': 'دكتورة سارة متخصصة في علاج عيوب النطق وتأخر الكلام لدى الأطفال بخبرة تزيد عن 10 سنوات.',
      'education': 'دكتوراه في علوم النطق والسمع - جامعة القاهرة',
      'price': '120 ج.م',
      'availableSlots': [
        {'date': '27 مارس', 'time': '10:00 صباحاً', 'available': true},
        {'date': '27 مارس', 'time': '11:00 صباحاً', 'available': true},
        {'date': '27 مارس', 'time': '02:00 مساءً', 'available': true},
        {'date': '28 مارس', 'time': '09:00 صباحاً', 'available': true},
        {'date': '28 مارس', 'time': '03:00 مساءً', 'available': false},
      ],
      'workingHours': '09:00 ص - 05:00 م',
      'experience': '10 سنوات',
    },
    {
      'id': 'doc_2',
      'name': 'د/ محمود علي',
      'specialty': 'تنمية مهارات وتعديل سلوك',
      'rating': 4.8,
      'reviewsCount': 120,
      'image': 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800',
      'about': 'دكتور محمود متخصص في برامج تنمية المهارات الإدراكية والاجتماعية للأطفال ذوي الاحتياجات الخاصة.',
      'education': 'ماجستير علم نفس الطفل - جامعة عين شمس',
      'price': '100 ج.م',
      'availableSlots': [
        {'date': '27 مارس', 'time': '10:00 صباحاً', 'available': true},
        {'date': '27 مارس', 'time': '12:00 مساءً', 'available': true},
        {'date': '28 مارس', 'time': '11:00 صباحاً', 'available': true},
        {'date': '28 مارس', 'time': '02:00 مساءً', 'available': true},
      ],
      'workingHours': '10:00 ص - 06:00 م',
      'experience': '8 سنوات',
    },
    {
      'id': 'doc_3',
      'name': 'د/ فاطمة حسن',
      'specialty': 'أخصائي تخاطب ونطق',
      'rating': 4.7,
      'reviewsCount': 95,
      'image': 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800',
      'about': 'دكتورة فاطمة متخصصة في علاج اضطرابات النطق واللغة لدى الأطفال، مع خبرة في استخدام أحدث التقنيات العلاجية.',
      'education': 'دكتوراه في علاج النطق واللغة - جامعة الإسكندرية',
      'price': '110 ج.م',
      'availableSlots': [
        {'date': '27 مارس', 'time': '09:00 صباحاً', 'available': true},
        {'date': '27 مارس', 'time': '01:00 مساءً', 'available': true},
        {'date': '28 مارس', 'time': '10:00 صباحاً', 'available': true},
      ],
      'workingHours': '09:00 ص - 04:00 م',
      'experience': '7 سنوات',
    },
    {
      'id': 'doc_4',
      'name': 'د/ خالد محمد',
      'specialty': 'تنمية مهارات وتعديل سلوك',
      'rating': 4.6,
      'reviewsCount': 80,
      'image': 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800',
      'about': 'دكتور خالد متخصص في برامج تعديل السلوك وتنمية المهارات الاجتماعية للأطفال.',
      'education': 'ماجستير علم نفس الطفل - جامعة الزقازيق',
      'price': '95 ج.م',
      'availableSlots': [
        {'date': '27 مارس', 'time': '11:00 صباحاً', 'available': true},
        {'date': '27 مارس', 'time': '03:00 مساءً', 'available': true},
        {'date': '28 مارس', 'time': '09:00 صباحاً', 'available': true},
      ],
      'workingHours': '10:00 ص - 05:00 م',
      'experience': '6 سنوات',
    },
  ];

  static const products = [
    {
      'id': 'prod_1',
      'name': 'مجموعة البطاقات التعليمية',
      'price': '85 ج.م',
      'oldPrice': '100 ج.م',
      'rating': 4.5,
      'reviewsCount': 45,
      'description': 'مجموعة من 50 بطاقة ملونة لتعليم الأسماء والأفعال الأساسية للأطفال. تساعد على تطوير المفردات والذاكرة البصرية.',
      'images': [
        'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800',
        'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800',
        'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
      ],
      'category': 'تعليمي',
      'inStock': true,
    },
    {
      'id': 'prod_2',
      'name': 'لعبة الأشكال الخشبية',
      'price': '150 ج.م',
      'rating': 4.8,
      'reviewsCount': 32,
      'description': 'لعبة تعليمية تساعد على تنمية المهارات الحركية الدقيقة والتعرف على الأشكال والألوان.',
      'images': [
        'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800',
        'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
      ],
      'category': 'ألعاب',
      'inStock': true,
    },
    {
      'id': 'prod_3',
      'name': 'كتاب القصص التفاعلي',
      'price': '120 ج.م',
      'oldPrice': '150 ج.م',
      'rating': 4.7,
      'reviewsCount': 28,
      'description': 'كتاب تفاعلي يحتوي على قصص مصورة مع أصوات وأضواء لتحفيز الطفل على القراءة والاستماع.',
      'images': [
        'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
      ],
      'category': 'كتب',
      'inStock': true,
    },
    {
      'id': 'prod_4',
      'name': 'مجموعة المكعبات الذكية',
      'price': '200 ج.م',
      'rating': 4.9,
      'reviewsCount': 67,
      'description': 'مكعبات ملونة بأحجام مختلفة تساعد على تطوير المهارات الحركية والإبداع والتفكير المنطقي.',
      'images': [
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800',
      ],
      'category': 'ألعاب',
      'inStock': true,
    },
    {
      'id': 'prod_5',
      'name': 'لوحة الأرقام والحروف',
      'price': '95 ج.م',
      'rating': 4.6,
      'reviewsCount': 41,
      'description': 'لوحة تعليمية تفاعلية لتعليم الأرقام والحروف العربية والإنجليزية مع أصوات مسجلة.',
      'images': [
        'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
        'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800',
      ],
      'category': 'تعليمي',
      'inStock': true,
    },
    {
      'id': 'prod_6',
      'name': 'مجموعة ألعاب الذاكرة',
      'price': '75 ج.م',
      'oldPrice': '90 ج.م',
      'rating': 4.4,
      'reviewsCount': 19,
      'description': 'مجموعة من ألعاب الذاكرة والتركيز المناسبة للأطفال لتنمية مهارات الذاكرة والانتباه.',
      'images': [
        'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800',
      ],
      'category': 'ألعاب',
      'inStock': false,
    },
  ];

  static const packages = [
    {
      'id': 'pkg_1',
      'title': 'الباقة الأساسية',
      'price': '450 ج.م',
      'duration': 'شهر واحد',
      'features': [
        '4 جلسات تخاطب (أونلاين)',
        'تقرير تقييم أسبوعي',
        'دعم عبر الواتساب',
      ],
      'isPopular': false,
    },
    {
      'id': 'pkg_2',
      'title': 'الباقة المتقدمة',
      'price': '1200 ج.م',
      'duration': '3 أشهر',
      'features': [
        '12 جلسة تخاطب (أونلاين)',
        'تقارير شهرية مفصلة',
        'جلسة استشارية مجانية للأهل',
        'خصم 10% على المتجر',
      ],
      'isPopular': true,
    },
  ];

  static const children = [
    {
      'id': 'child_1',
      'name': 'عمر محمد',
      'age': 6,
      'birthDate': '2018-05-15',
      'gender': 'male',
      'status': 'تخاطب',
      'progress': 0.68,
      'imageUrl': 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=400',
      'assessments': [
        {
          'id': 'assess_1',
          'name': 'تقييم النطق',
          'date': '2024-01-15',
          'score': 75,
          'status': 'completed',
        },
        {
          'id': 'assess_2',
          'name': 'تقييم المهارات الإدراكية',
          'date': '2024-01-20',
          'score': 82,
          'status': 'completed',
        },
      ],
      'sessions': 12,
      'nextSession': '2024-02-10 10:00',
    },
    {
      'id': 'child_2',
      'name': 'سارة أحمد',
      'age': 5,
      'birthDate': '2019-03-20',
      'gender': 'female',
      'status': 'تنمية مهارات',
      'progress': 0.45,
      'imageUrl': 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
      'sessions': 8,
      'nextSession': '2024-02-12 14:00',
    },
  ];

  static const appointments = [
    {
      'id': 'app_1',
      'status': 'UPCOMING',
      'date': '2024-02-10',
      'time': '10:00 صباحاً',
      'dateDisplay': 'السبت 10 فبراير • 10:00 صباحاً',
      'title': 'جلسة تخاطب',
      'type': 'فيديو',
      'doctorId': 'doc_1',
      'doctorName': 'د/ سارة أحمد',
      'doctorImage': 'https://images.unsplash.com/photo-1559839734-2b71f1536783?w=800',
      'doctorSpecialty': 'أخصائي تخاطب ونطق',
      'price': '120 ج.م',
      'duration': '45 دقيقة',
      'childId': 'child_1',
      'childName': 'عمر محمد',
      'notes': 'يرجى تجهيز الطفل قبل الجلسة بـ 10 دقائق وتوفير بيئة هادئة.',
    },
    {
      'id': 'app_2',
      'status': 'COMPLETED',
      'date': '2024-01-28',
      'time': '02:00 مساءً',
      'dateDisplay': 'الأحد 28 يناير • 02:00 مساءً',
      'title': 'جلسة تنمية مهارات',
      'type': 'فيديو',
      'doctorId': 'doc_2',
      'doctorName': 'د/ محمود علي',
      'doctorImage': 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800',
      'doctorSpecialty': 'تنمية مهارات وتعديل سلوك',
      'price': '100 ج.م',
      'duration': '45 دقيقة',
      'childId': 'child_2',
      'childName': 'سارة أحمد',
      'rating': 5,
      'review': 'جلسة ممتازة، الدكتور محترف جداً',
    },
    {
      'id': 'app_3',
      'status': 'CANCELLED',
      'date': '2024-01-25',
      'time': '11:00 صباحاً',
      'dateDisplay': 'الخميس 25 يناير • 11:00 صباحاً',
      'title': 'جلسة تخاطب',
      'type': 'فيديو',
      'doctorId': 'doc_1',
      'doctorName': 'د/ سارة أحمد',
      'doctorImage': 'https://images.unsplash.com/photo-1559839734-2b71f1536783?w=800',
      'doctorSpecialty': 'أخصائي تخاطب ونطق',
      'price': '120 ج.م',
      'childId': 'child_1',
      'childName': 'عمر محمد',
      'cancelReason': 'ظرف طارئ',
    },
  ];

  static const orders = [
    {
      'id': 'order_1',
      'orderNumber': '#12345',
      'status': 'DELIVERED',
      'date': '2024-01-15',
      'dateDisplay': '15 يناير 2024',
      'total': '305 ج.م',
      'items': [
        {
          'productId': 'prod_1',
          'name': 'مجموعة البطاقات التعليمية',
          'price': '85 ج.م',
          'quantity': 2,
          'image': 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800',
        },
        {
          'productId': 'prod_3',
          'name': 'كتاب القصص التفاعلي',
          'price': '120 ج.م',
          'quantity': 1,
          'image': 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
        },
      ],
      'shippingAddress': 'شارع التحرير، المعادي، القاهرة',
      'paymentMethod': 'بطاقة ائتمان',
      'shippingFee': '15 ج.م',
      'trackingNumber': 'TRK123456789',
      'deliveryDate': '2024-01-18',
    },
    {
      'id': 'order_2',
      'orderNumber': '#12346',
      'status': 'SHIPPING',
      'date': '2024-01-28',
      'dateDisplay': '28 يناير 2024',
      'total': '350 ج.م',
      'items': [
        {
          'productId': 'prod_2',
          'name': 'لعبة الأشكال الخشبية',
          'price': '150 ج.م',
          'quantity': 1,
          'image': 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800',
        },
        {
          'productId': 'prod_4',
          'name': 'مجموعة المكعبات الذكية',
          'price': '200 ج.م',
          'quantity': 1,
          'image': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        },
      ],
      'shippingAddress': 'شارع التحرير، المعادي، القاهرة',
      'paymentMethod': 'نقداً عند الاستلام',
      'shippingFee': '0 ج.م',
      'trackingNumber': 'TRK123456790',
      'estimatedDelivery': '2024-02-02',
    },
    {
      'id': 'order_3',
      'orderNumber': '#12347',
      'status': 'PENDING',
      'date': '2024-02-01',
      'dateDisplay': '1 فبراير 2024',
      'total': '195 ج.م',
      'items': [
        {
          'productId': 'prod_5',
          'name': 'لوحة الأرقام والحروف',
          'price': '95 ج.م',
          'quantity': 2,
          'image': 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
        },
      ],
      'shippingAddress': 'شارع التحرير، المعادي، القاهرة',
      'paymentMethod': 'بطاقة ائتمان',
      'shippingFee': '5 ج.م',
    },
  ];

  static const cartItems = [
    {
      'id': 'cart_1',
      'productId': 'prod_1',
      'name': 'مجموعة البطاقات التعليمية',
      'price': 85.0,
      'oldPrice': 100.0,
      'quantity': 1,
      'image': 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800',
      'inStock': true,
    },
    {
      'id': 'cart_2',
      'productId': 'prod_4',
      'name': 'مجموعة المكعبات الذكية',
      'price': 200.0,
      'quantity': 1,
      'image': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      'inStock': true,
    },
  ];

  static const favorites = [
    {
      'id': 'fav_1',
      'productId': 'prod_2',
      'name': 'لعبة الأشكال الخشبية',
      'price': '150 ج.م',
      'rating': 4.8,
      'image': 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800',
      'inStock': true,
    },
    {
      'id': 'fav_2',
      'productId': 'prod_3',
      'name': 'كتاب القصص التفاعلي',
      'price': '120 ج.م',
      'oldPrice': '150 ج.م',
      'rating': 4.7,
      'image': 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
      'inStock': true,
    },
  ];

  static const reviews = [
    {
      'id': 'review_1',
      'productId': 'prod_1',
      'userName': 'أحمد محمد',
      'userImage': 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
      'rating': 5.0,
      'date': '2024-01-20',
      'comment': 'منتج ممتاز! ساعد طفلي كثيراً في تطوير مهاراته اللغوية.',
      'helpful': 12,
    },
    {
      'id': 'review_2',
      'productId': 'prod_1',
      'userName': 'فاطمة علي',
      'userImage': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
      'rating': 4.0,
      'date': '2024-01-18',
      'comment': 'جيد جداً، لكن كنت أتمنى أن تكون البطاقات أكبر حجماً.',
      'helpful': 8,
    },
  ];

  static const faqs = [
    {
      'id': 'faq_1',
      'question': 'كيف يمكنني حجز جلسة؟',
      'answer': 'يمكنك حجز جلسة من خلال صفحة الأخصائيين، اختر الأخصائي المناسب ثم اختر الموعد المتاح.',
      'category': 'الحجز',
    },
    {
      'id': 'faq_2',
      'question': 'ما هي طرق الدفع المتاحة؟',
      'answer': 'نوفر الدفع عبر البطاقات الائتمانية، فودافون كاش، والدفع نقداً عند الاستلام للمنتجات.',
      'category': 'الدفع',
    },
    {
      'id': 'faq_3',
      'question': 'هل يمكنني إلغاء الجلسة؟',
      'answer': 'نعم، يمكنك إلغاء الجلسة قبل 24 ساعة من موعدها لاسترداد المبلغ كاملاً.',
      'category': 'الحجز',
    },
    {
      'id': 'faq_4',
      'question': 'كم تستغرق مدة التوصيل؟',
      'answer': 'عادة ما يستغرق التوصيل من 2-5 أيام عمل حسب موقعك.',
      'category': 'الشحن',
    },
    {
      'id': 'faq_5',
      'question': 'هل التقييمات مجانية؟',
      'answer': 'نعم، نوفر تقييم أولي مجاني لتحديد احتياجات طفلك.',
      'category': 'التقييمات',
    },
  ];

  static const maharaActivities = [
    {
      'id': 'activity_1',
      'type': 'LISTEN_CHOOSE',
      'title': 'اختر الصورة الصحيحة',
      'instruction': 'استمع للصوت واختر الصورة المناسبة',
      'audioUrl': 'https://example.com/audio/sound1.mp3',
      'correctImageId': 'img_1',
      'images': [
        {
          'id': 'img_1',
          'url': 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
          'label': 'قطة',
        },
        {
          'id': 'img_2',
          'url': 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400',
          'label': 'كلب',
        },
      ],
    },
    {
      'id': 'activity_2',
      'type': 'MATCHING',
      'title': 'طابق الصور',
      'instruction': 'اسحب كل صورة إلى الصورة المطابقة لها',
      'pairs': [
        {
          'leftId': 'left_1',
          'leftImage': 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=400',
          'rightId': 'right_1',
          'rightImage': 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=400',
        },
        {
          'leftId': 'left_2',
          'leftImage': 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400',
          'rightId': 'right_2',
          'rightImage': 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400',
        },
      ],
    },
    {
      'id': 'activity_3',
      'type': 'SEQUENCE',
      'title': 'رتب الصور',
      'instruction': 'اسحب الصور لترتيبها بشكل صحيح',
      'items': [
        {
          'id': 'seq_1',
          'image': 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=400',
          'order': 1,
        },
        {
          'id': 'seq_2',
          'image': 'https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?w=400',
          'order': 2,
        },
        {
          'id': 'seq_3',
          'image': 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
          'order': 3,
        },
      ],
    },
  ];

  static const addresses = [
    {
      'id': 'addr_1',
      'label': 'المنزل',
      'street': 'شارع التحرير',
      'city': 'المعادي',
      'area': 'القاهرة',
      'buildingNumber': '15',
      'floor': '3',
      'apartment': '5',
      'phone': '01012345678',
      'isDefault': true,
    },
    {
      'id': 'addr_2',
      'label': 'العمل',
      'street': 'شارع الجامعة',
      'city': 'الجيزة',
      'area': 'الدقي',
      'buildingNumber': '20',
      'floor': '1',
      'phone': '01098765432',
      'isDefault': false,
    },
  ];

  static const chatConversations = [
    {
      'id': 'chat_1',
      'doctorId': 'doc_1',
      'doctorName': 'د/ سارة أحمد',
      'doctorImage': 'https://images.unsplash.com/photo-1559839734-2b71f1536783?w=800',
      'lastMessage': 'شكراً لك، نلتقي في الجلسة القادمة',
      'lastMessageTime': 'منذ 5 دقائق',
      'unreadCount': 0,
      'isOnline': true,
    },
    {
      'id': 'chat_2',
      'doctorId': 'doc_2',
      'doctorName': 'د/ محمود علي',
      'doctorImage': 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800',
      'lastMessage': 'هل يمكننا تغيير موعد الجلسة؟',
      'lastMessageTime': 'منذ ساعة',
      'unreadCount': 2,
      'isOnline': false,
    },
  ];

  static const chatMessages = [
    {
      'id': 'msg_1',
      'chatId': 'chat_1',
      'senderId': 'user_1',
      'senderType': 'user',
      'message': 'مرحباً دكتورة، متى يمكننا البدء بالجلسة؟',
      'timestamp': '2024-02-01 10:00',
      'isRead': true,
    },
    {
      'id': 'msg_2',
      'chatId': 'chat_1',
      'senderId': 'doc_1',
      'senderType': 'doctor',
      'message': 'مرحباً، يمكننا البدء يوم السبت الساعة 10 صباحاً',
      'timestamp': '2024-02-01 10:05',
      'isRead': true,
    },
    {
      'id': 'msg_3',
      'chatId': 'chat_1',
      'senderId': 'user_1',
      'senderType': 'user',
      'message': 'ممتاز، شكراً لك',
      'timestamp': '2024-02-01 10:10',
      'isRead': true,
    },
  ];

  static const assessmentCategories = [
    {
      'id': 'cat_1',
      'name': 'التقييم اللغوي',
      'description': 'تقييم شامل للمهارات اللغوية والنطق',
      'icon': 'language',
      'testsCount': 5,
      'duration': '30-45 دقيقة',
    },
    {
      'id': 'cat_2',
      'name': 'التقييم الإدراكي',
      'description': 'تقييم المهارات الإدراكية والتفكير',
      'icon': 'brain',
      'testsCount': 7,
      'duration': '45-60 دقيقة',
    },
    {
      'id': 'cat_3',
      'name': 'التقييم الاجتماعي',
      'description': 'تقييم المهارات الاجتماعية والتفاعل',
      'icon': 'people',
      'testsCount': 4,
      'duration': '20-30 دقيقة',
    },
  ];

  static const supportTickets = [
    {
      'id': 'ticket_1',
      'subject': 'مشكلة في الدفع',
      'status': 'OPEN',
      'priority': 'HIGH',
      'date': '2024-02-01',
      'lastUpdate': 'منذ ساعتين',
      'messages': [
        {
          'id': 'tmsg_1',
          'sender': 'user',
          'message': 'لم أتمكن من إكمال عملية الدفع',
          'timestamp': '2024-02-01 09:00',
        },
        {
          'id': 'tmsg_2',
          'sender': 'support',
          'message': 'نعتذر عن الإزعاج، سنقوم بالتحقق من المشكلة',
          'timestamp': '2024-02-01 09:30',
        },
      ],
    },
    {
      'id': 'ticket_2',
      'subject': 'استفسار عن الجلسات',
      'status': 'CLOSED',
      'priority': 'NORMAL',
      'date': '2024-01-28',
      'lastUpdate': 'منذ 3 أيام',
    },
  ];
}
